name: agifog
version: v1.0.0
title: agi fog
description: Service to talk to aws
documentationLink: https://github.com/restebanez/agifog
protocol: rest
basePath: /api/v1/
resources: 
  rds_servers: 
    methods: 
      list: 
        id: agifog.rds_servers.list
        path: rds/servers
        httpMethod: GET
        description: Gets every rds server
        parameters: {}

      show: 
        id: agifog.rds_servers.show
        path: rds/servers/{id}
        httpMethod: GET
        description: Gets a rds server
        parameters: 
          id: 
            description: rds server id
      create: 
        id: agifog.rds_servers.create
        path: rds/servers
        httpMethod: POST
        description: Create a new rds server
        parameters: {}

  rds_security_groups: 
    methods: 
      list: 
        id: agifog.rds_security_groups.list
        path: rds/security_groups
        httpMethod: GET
        description: Gets every rds security group
        parameters: {}

      show: 
        id: agifog.rds_security_groups.show
        path: rds/security_groups/{id}
        httpMethod: GET
        description: Gets a security group server
        parameters: 
          id: 
            description: rds security group id
      authorize: 
        id: agifog.rds_security_groups.authorize
        path: rds/security_groups/{id}/authorize
        httpMethod: PUT
        description: Authorize a security group server
        parameters: 
          id: 
            description: rds authorize a security group id
