name: agifog
version: v1.0.0
title: agi fog
description: Service to talk to aws
documentationLink: https://github.com/restebanez/agifog
protocol: rest
basePath: /api/v1/
resources: 
  rds_servers: 
    methods: 
      list: 
        id: agifog.rds_servers.list
        path: rds/servers
        httpMethod: GET
        description: Gets every rds server
        parameters: {}

      show: 
        id: agifog.rds_servers.show
        path: rds/servers/{id}
        httpMethod: GET
        description: Gets a rds server
        parameters: 
          id: 
            description: rds server id
      create: 
        id: agifog.rds_servers.create
        path: rds/servers
        httpMethod: POST
        description: Create a new rds server
        parameters: {}

  rds_security_groups: 
    methods: 
      list: 
        id: agifog.rds_security_groups.list
        path: rds/security_groups
        httpMethod: GET
        description: Gets every rds security group
        parameters: {}

      show: 
        id: agifog.rds_security_groups.show
        path: rds/security_groups/{id}
        httpMethod: GET
        description: Gets a security group server
        parameters: 
          id: 
            description: rds security group id
      authorize: 
        id: agifog.rds_security_groups.authorize
        path: rds/security_groups/{id}/authorize
        httpMethod: PUT
        description: Authorize a security group server
        parameters: 
          id: 
            description: rds authorize a security group id
  iam_users:
    methods:
      list:
        id: agifog.iam_users.list
        path: iam/users
        httpMethod: GET
      show:
        id: agifog.iam_users.show
        path: iam/users/{id}
        httpMethod: GET
      create:
        id: agifog.iam_users.create
        path: iam/users
        httpMethod: POST
      delete:
        id: agifog.iam_users.delete
        path: iam/users/{id}
        httpMethod: DELETE
  iam_users_policies:
    methods:
      list:
        id: agifog.iam_users_policies.list
        path: iam/users/{user_id}/policies
        httpMethod: GET
      show:
        id: agifog.iam_users_policies.show
        path: iam/users/{user_id}/policies/{id}
        httpMethod: GET
      create:
        id: agifog.iam_users_policies.create
        path: iam/users/{user_id}/policies
        httpMethod: POST
      delete:
        id: agifog.iam_users_policies.delete
        path: iam/users/{user_id}/policies/{id}
        httpMethod: DELETE
  iam_users_access_keys:
    methods:
      list:
        id: agifog.iam_users_access_keys.list
        path: iam/users/{user_id}/access_keys
        httpMethod: GET
      show:
        id: agifog.iam_users_access_keys.show
        path: iam/users/{user_id}/access_keys/{id}
        httpMethod: GET
      create:
        id: agifog.iam_users_access_keys.create
        path: iam/users/{user_id}/access_keys
        httpMethod: POST
      delete:
        id: agifog.iam_users_access_keys.delete
        path: iam/users/{user_id}/access_keys/{id}
        httpMethod: DELETE
